---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echoup-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: echoup-dev
  chart:
    git: git@github.com:ThreatACC/helm-operator-get-started.git
    path: charts/echoup
    ref: master
  values:
    image:
      repository: gcr.io/fine-balm-322411/echoup
      tag: dev-qkzdnvow
    replicaCount: 1
    hpa:
      enabled: false
