# Default values for echoup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gcr.io/fine-balm-322411/echo-v5
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  porthttp: 80
  porttls: 443
  targetPort: 3000
ingress:
  enabled: true
  annotations: 
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: www.knowyourcity.net
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - secretName: letsencrypt-prod
      hosts:
        - www.knowyourcity.net

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

secret:
  urlkey: mongo-db-url
  envname: MONGODBURL
  name: mongodb-secret

confmap:
  name:  myconfigmap
  persistKey: PERSIST
  logLevelKey: LOGLEVEL

cert:
  isStaging: true
  server:
    prod: https://acme-v02.api.letsencrypt.org/directory
    stage: https://acme-staging-v02.api.letsencrypt.org/directory
  email: thekingoftheworld@TheOtherGoldenPalace.xyz

cleaner:
  restartPolicy: OnFailure
  schedule: "1 0 * * *"

storageClass:
  name: &scname "slow"
  provisioner: kubernetes.io/gce-pd
  gcp:
    type: pd-standard
    fstype: xfs
  replicationtype: none

mongodb:
  architecture: replicaset
  useStatefulSet: true
  auth:
    rootPassword: "rootpass"
    username: "username"
    password: "password"
    database: "echo"
    replicaSetKey: "dg9CxJWOnuprgQ=="
  replicaSetName: MainRepSet
  replicaCount: 3
  service:
    nameOverride: "mongodb-headless"
    clusterIP: "None"
  persistence:
    storageClass: *scname
    size: 1Gi
  arbiter:
    enabled: false

