---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echup-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: echup-rc
  chart:
    git: git@github.com:ThreatACC/helm-operator-get-started.git 
    path: charts/echup
    ref: master
  values:
    image:
      repository: gcr.io/fine-balm-322411/echup
      tag: stg-9ij63o4c
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
