apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
  # The ACME server URL
    server: {{ ternary .Values.cert.server.stage .Values.cert.server.prod .Values.cert.isStaging }}
  # Email address used for ACME registration
    email: {{ .Values.cert.email }}
  # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  nginx
