---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name  }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  {{- if eq .Values.storageClass.provisioner "kubernetes.io/gce-pd" }}
  type: {{ .Values.storageClass.gcp.type }}
  fstype: {{ .Values.storageClass.gcp.fstype }}
  replication-type: {{ .Values.storageClass.replicationtype }}
  {{- end }}