---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongo-db-url: 'mongodb://username:password@mongodb-headless/echo?authSource=echo&ReplicaSet=MainRepSet'
  username: 'username'
  password: 'password'