apiVersion: v1
kind: Service
metadata:
  name: {{ include "echoup.fullname" . }}
  labels:
    {{- include "echoup.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.porthttp }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.porttls }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "echoup.selectorLabels" . | nindent 4 }}
